### ISSUE TITLE
how/can we include pods

### ISSUE THREAD

**Issue by jrdaher** [sersoft-gmbh/xcodebuild-action#91]
my project has cocoa pods dependencies that need to be built before it can run, how can I include those ?

**Comment by ffried** [comment]
This action just runs the `xcodebuild` command.
If the CocoaPods dependencies are already present in the repository, you don't need to do anything except passing the workspace (instead of the project) to this action (using the `workspace` input instead of `project`).

Any special tasks that need to be done before building should be done in a separate `run` step inside your action.

**Comment by ffried** [comment]
Did this work out for you? I'm closing this, since IMHO there's nothing this action should do here. Feel free to re-open it if you still encounter issues.
